name: Deploy to Staging

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  NODE_VERSION: "20.x"
  FIREBASE_PROJECT_STAGING: "zk-vault-staging"

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://zk-vault-staging.web.app
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests and linting
        run: |
          npm run lint
          npm run type-check
          npm run test

      - name: Build packages
        run: |
          npm run build
        env:
          NODE_ENV: staging
          REACT_APP_ENVIRONMENT: staging

      - name: Setup Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Staging
        run: |
          firebase use ${{ env.FIREBASE_PROJECT_STAGING }}
          firebase deploy --only hosting,functions,firestore:rules,storage:rules
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_STAGING }}

      - name: Deploy browser extension to staging
        run: |
          # Build extension for staging
          cd packages/browser-extension
          npm run build:staging
          # Archive extension for manual distribution or store upload
          zip -r zk-vault-extension-staging.zip dist/
        continue-on-error: true

      - name: Upload staging artifacts
        uses: actions/upload-artifact@v3
        with:
          name: staging-build-${{ github.sha }}
          path: |
            packages/*/dist/
            packages/browser-extension/*.zip
          retention-days: 7

      - name: Notify deployment status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "✅ Staging deployment successful!"
            echo "🔗 Staging URL: https://zk-vault-staging.web.app"
          else
            echo "❌ Staging deployment failed!"
          fi
