#!/bin/bash

# =============================================================
# ZK-VAULT FIREBASE SETUP SCRIPT
# =============================================================
# This script helps you set up Firebase and get your environment variables

set -e

echo "🔥 ZK-Vault Firebase Setup Helper"
echo "=================================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if Firebase CLI is installed
if ! command -v firebase &> /dev/null; then
    echo -e "${YELLOW}Firebase CLI not found. Installing...${NC}"
    npm install -g firebase-tools
fi

echo -e "${BLUE}Step 1: Login to Firebase${NC}"
echo "----------------------------------------"
firebase login

echo ""
echo -e "${BLUE}Step 2: List your Firebase projects${NC}"
echo "----------------------------------------"
firebase projects:list

echo ""
echo -e "${YELLOW}Do you want to create a new Firebase project? (y/N)${NC}"
read -r create_new

if [[ $create_new =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Creating new Firebase project...${NC}"
    echo "Enter your project ID (lowercase, no spaces):"
    read -r project_id
    
    # Note: Project creation via CLI requires additional setup
    echo -e "${RED}Please create the project manually at: https://console.firebase.google.com${NC}"
    echo "Project ID: $project_id"
    echo "Then run this script again."
    exit 0
fi

echo ""
echo -e "${BLUE}Step 3: Select your Firebase project${NC}"
echo "----------------------------------------"
echo "Enter your Firebase project ID:"
read -r project_id

firebase use "$project_id"

echo ""
echo -e "${BLUE}Step 4: Enable required Firebase services${NC}"
echo "----------------------------------------"
echo "Enabling Authentication, Firestore, and Storage..."

# This would require the Firebase Management API
echo -e "${YELLOW}Please manually enable these services in Firebase Console:${NC}"
echo "1. Authentication (Email/Password, Google)"
echo "2. Firestore Database"
echo "3. Storage"
echo "4. Hosting"
echo ""
echo "Go to: https://console.firebase.google.com/project/$project_id"

echo ""
echo -e "${BLUE}Step 5: Get your Firebase configuration${NC}"
echo "----------------------------------------"
echo "Getting Firebase app configuration..."

# Get Firebase config (requires a web app to exist)
echo -e "${YELLOW}Please get your Firebase config from:${NC}"
echo "1. Go to: https://console.firebase.google.com/project/$project_id/settings/general"
echo "2. Scroll to 'Your apps' section"
echo "3. Click 'Add app' if no web app exists, or click on existing web app"
echo "4. Copy the configuration values"

echo ""
echo -e "${BLUE}Step 6: Create your .env.local file${NC}"
echo "----------------------------------------"

ENV_FILE="packages/web-app/.env.local"

echo "Creating $ENV_FILE..."

cat > "$ENV_FILE" << EOF
# =============================================================
# ZK-VAULT ENVIRONMENT VARIABLES
# =============================================================
# Generated by setup script

# Core Settings
NODE_ENV=development
DEBUG=true
LOG_LEVEL=info

# Firebase Configuration
# Replace these with your actual values from Firebase Console
VITE_FIREBASE_API_KEY=your-firebase-api-key-here
VITE_FIREBASE_AUTH_DOMAIN=$project_id.firebaseapp.com
VITE_FIREBASE_PROJECT_ID=$project_id
VITE_FIREBASE_STORAGE_BUCKET=$project_id.appspot.com
VITE_FIREBASE_MESSAGING_SENDER_ID=your-messaging-sender-id
VITE_FIREBASE_APP_ID=your-app-id

# Backend
FIREBASE_PROJECT_ID=$project_id

# Development
VITE_USE_EMULATORS=true
VITE_ENABLE_DEBUG_LOGS=true
VITE_API_URL=http://localhost:3000/api

# Emulator
FIREBASE_EMULATOR_HUB=0.0.0.0:4400
EOF

echo -e "${GREEN}✅ Created $ENV_FILE${NC}"
echo ""
echo -e "${YELLOW}⚠️  IMPORTANT: You still need to:${NC}"
echo "1. Replace the placeholder values in $ENV_FILE with your actual Firebase config"
echo "2. Get your config from: https://console.firebase.google.com/project/$project_id/settings/general"
echo ""
echo -e "${BLUE}Step 7: Initialize Firebase in your project${NC}"
echo "----------------------------------------"
firebase init

echo ""
echo -e "${GREEN}🎉 Firebase setup complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "1. Edit $ENV_FILE with your actual Firebase config values"
echo "2. Run: npm install"
echo "3. Run: npm run dev"
echo ""
echo -e "${YELLOW}Need help? Check the Firebase Console:${NC}"
echo "https://console.firebase.google.com/project/$project_id" 